image: fpco/stack-build:latest
cache:
  paths:
    - .stack/
    - .stack-work/

build:
  stage: build
  script:
    - apt-get update -y
    - stack setup
    - stack install cabal-install
    - stack build
    - stack haddock --haddock-deps --haddock-hyperlink-source
