name:                typograffiti-gl
version:             0.2.0.0
github:              "schell/typograffiti"
license:             BSD3
author:              "Schell Scivally"
maintainer:          "schell@takt.com"
copyright:           "2018 Schell Scivally"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            Just let me draw nice text already!
category:            Graphics

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         This is a text rendering library that uses OpenGL
                     and freetype2 to render TTF font strings quickly. It is
                     fast enough to render large chunks of text in real
                     time. This library exists because text rendering is
                     one of the biggest hurdles in Haskell graphics
                     programming - and it shouldn't be!

                     typograffiti-gl includes an MTL style typeclass and a
                     default monad transformer. It does not assume you are
                     using any specific windowing solution. It does assume
                     you are using OpenGL 3.3+ and have freetype2 installed.

dependencies:
- base >= 4.7 && < 5
- bytestring >= 0.10
- containers >= 0.6
- freetype2 >= 0.1
- gl >= 0.8
- linear >= 1.20
- mtl >= 2.2
- pretty-show >= 1.9
- stm >= 2.5
- template-haskell >= 2.14
- vector >= 0.12
- typograffiti-core
- typograffiti-freetype

library:
  source-dirs: src

executables:
  typograffiti-gl-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - filepath >= 1.4
    - pretty-show >= 1.9
    - sdl2 >= 2.4
    - typograffiti-gl


tests:
  typograffiti-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - typograffiti-gl
